
### USERS
GET http://localhost:1234/signup

###
GET http://localhost:1234/signup/4

### CREATE
POST http://localhost:1234/signup
Content-Type: application/json

{
  "name":"juan2",
  "email":"juan2@mail.co",
  "password": "111111"
}

### LOGIN
POST http://localhost:1234/login
Content-Type: application/json

{
  "email":"juan@mail.co",
  "password":"11111"
}
### DATA
GET http://localhost:1234/data